### ISSUE TITLE
NameError: name 'extra_compile_args' is not defined

### ISSUE THREAD

**Issue by sahwa** [Genomics-HSE/LaNeta#2]
Hi,

I'm trying to build the library and after successfully installing the dependencies as in the README,

```
$ python3 setup.py build_ext -i
```
This returns the error:

> Traceback (most recent call last):
>   File "/SAN/ghlab/pophistory/Sam/programs/LaNeta/setup.py", line 17, in <module>
>     extra_compile_args=extra_compile_args,
> NameError: name 'extra_compile_args' is not defined
> 

I am running this on Red Hat 4.8.5-44 and Python 3.9.7.

Any idea what might be causing this?

Thanks,

Sam

**Comment by TesMichelle** [comment]
Hi,
Now you can download new version of LaNeta and run it.
Wait for your feedback.

**Comment by sahwa** [comment]
Hi, thanks for the response. Unfortunately I still get an error:

```
running build_ext
cythoning LaNeta/fastc.pyx to LaNeta/fastc.c
warning: LaNeta/fastc.pyx:896:48: Index should be typed for more efficient access
error: Command "gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -O2 -ftree-vectorize -march=native -fno-math-errno -fPIC -fPIC -I/apps/eb/2020b/skylake/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/numpy/core/include -I/apps/eb/2020b/skylake/software/Python/3.9.6-GCCcore-11.2.0/include/python3.9 -c LaNeta/fastc.c -o build/temp.linux-x86_64-3.9/LaNeta/fastc.o " failed with exit status 1
```

Also tried it on a different system:

```
running build_ext
cythoning LaNeta/fastc.pyx to LaNeta/fastc.c
warning: LaNeta/fastc.pyx:896:48: Index should be typed for more efficient access
building 'LaNeta.fastc' extension
creating build
creating build/temp.linux-x86_64-3.9
creating build/temp.linux-x86_64-3.9/LaNeta
/SAN/ghlab/pophistory/Sam/programs/miniconda3/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /SAN/ghlab/pophistory/Sam/programs/miniconda3/include -I/SAN/ghlab/pophistory/Sam/programs/miniconda3/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /SAN/ghlab/pophistory/Sam/programs/miniconda3/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /SAN/ghlab/pophistory/Sam/programs/miniconda3/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /SAN/ghlab/pophistory/Sam/programs/miniconda3/include -fPIC -I/SAN/ghlab/pophistory/Sam/programs/miniconda3/lib/python3.9/site-packages/numpy/core/include -I/SAN/ghlab/pophistory/Sam/programs/miniconda3/include/python3.9 -c LaNeta/fastc.c -o build/temp.linux-x86_64-3.9/LaNeta/fastc.o
x86_64-conda-linux-gnu-cc: error: : No such file or directory
error: command '/SAN/ghlab/pophistory/Sam/programs/miniconda3/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
```

**Comment by TesMichelle** [comment]
Hi,
We made new installation with building python extension. 
May you clone the 'test' branch and walk through the installation described there?

**Comment by sahwa** [comment]
Hi, sorry about the delay.

I did the following 

```
conda create -n conda_laneta
conda activate conda_laneta
conda install python=3.9    

git clone -b test https://github.com/Genomics-HSE/LaNeta.git
cd LaNeta 

python -m pip install .
```
Which returned:

```
Processing /SAN/ghlab/pophistory/Sam/programs/LaNeta
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cyvcf2
  Using cached cyvcf2-0.30.16-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.8 MB)
Collecting numpy>=1.19.5
  Using cached numpy-1.23.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting coloredlogs
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting humanfriendly>=9.1
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Building wheels for collected packages: LaNeta
  Building wheel for LaNeta (pyproject.toml) ... done
  Created wheel for LaNeta: filename=LaNeta-3.0-py3-none-any.whl size=3013 sha256=bced9f2c21dd8385320d00e47a13b20562e0846050d1fa859d45a156f0ce13f7
  Stored in directory: /tmp/pip-ephem-wheel-cache-dfq926tm/wheels/97/75/e5/5adcb574358b12eaea60f0030f674d1f04526c23b736c5b283
Successfully built LaNeta
Installing collected packages: numpy, humanfriendly, click, coloredlogs, cyvcf2, LaNeta
Successfully installed LaNeta-3.0 click-8.1.3 coloredlogs-15.0.1 cyvcf2-0.30.16 humanfriendly-10.0 numpy-1.23.2
```

However, when I run:

```
python laneta.py
```

I get 

```
Traceback (most recent call last):
  File "/SAN/ghlab/pophistory/Sam/programs/LaNeta/laneta.py", line 5, in <module>
    from LaNeta.ThLd import LaNeta
  File "/SAN/ghlab/pophistory/Sam/programs/LaNeta/LaNeta/ThLd.py", line 1, in <module>
    from LaNeta.fastc import binning_b, binning_c, FFT, thld_6, binning_deltas, estimate_frequencies_c, estimate_deltas_c, \
ModuleNotFoundError: No module named 'LaNeta.fastc'
```

**Comment by TesMichelle** [comment]
Hi, 
It was my mistake, please clone new version!

**Comment by sahwa** [comment]
Great - it's working now! Thanks for your quick response! The only thing is I had to manually install the scipy dependency, but apart from that it seems to be running fine.
