### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by jiangzy26** [Genomics-HSE/LaNeta#3]
Hi,
    When I run LaNeta, I got one TypeError, could you share your help?
    Here is the output:

Starting LaNeta...
estimating weighted LD...
CHR_N: 1
[0.00000000e+00 9.21276639e-22 1.04500181e-21 ... 1.54929056e-04
 1.54930421e-04 1.54934516e-04]
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... -2  0  0]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  1  0  0]]
[0.00000000e+00 9.21276639e-22 1.04500181e-21 ... 1.54929056e-04
 1.54930421e-04 1.54934516e-04]
0:00:07.289282 - data read.
0
Traceback (most recent call last):
  File "/home/8-LaNeta/LaNeta/laneta.py", line 118, in <module>
    Mt=clargs.mt)
  File "/home/8-LaNeta/LaNeta/LaNeta/ThLd.py", line 710, in estimateTwoPulse
    freq_filter=freq_filter, Mt=Mt, at=at)
  File "/home/8-LaNeta/LaNeta/LaNeta/ThLd.py", line 469, in estimate
    numerator_i = alg.estimate_numerator()
  File "/home/8-LaNeta/LaNeta/LaNeta/ThLd.py", line 347, in estimate_numerator
    b = self.estimate_bin_b_int() #no epsilon during binning
  File "/home/8-LaNeta/LaNeta/LaNeta/ThLd.py", line 294, in estimate_bin_b_int
    m=WLD.Mt, missing_ref=WLD.data.missing_ref) )
  File "LaNeta/fastc.pyx", line 637, in LaNeta.fastc.binning_b_int
TypeError: must be real number, not NoneType

**Comment by zhen0506** [comment]
Hi,
The same error occurred during my run. Did you figure out the issue?

**Comment by TesMichelle** [comment]
Hi,
Now you can download new version of LaNeta and run it.
Wait for your feedback.
