### ISSUE TITLE
ValueError: Residuals are not finite in the initial point.

### ISSUE THREAD

**Issue by YiBenqiu** [Genomics-HSE/LaNeta#5]
**Hi there.**
 
I use `plink --50 10 0.3` to prune the SNP, and POS_MORGANS  of a SNP was estimated by dividing the position coordinate by 1,000,000. 

Then enter following command:
`python3.9 ~/LaNeta-main/laneta.py -vcf cleanBinaryPruned.vcf.gz -p pop_used -m morgan.map -p0 LEW -p1 WBE -p2 CNS`

**Output:**
`Starting LaNeta...
The number of chromosomes (contigs in .vcf HEADER): 18

Two Pulse Model:
LEW - admixed population! Sample size: 30
WBE - admixed one time! Sample size: 10
CNS - admixed two times! Sample size: 16

estimating weighted LD...
CHR: 1
variants count (.vcf): 77109
77109
0:00:07.356741 - data read.
0:00:10.882610 - estimation.
1/18
CHR: 2
variants count (.vcf): 60246
60246
0:00:05.791607 - data read.
0:00:04.188145 - estimation.
2/18
CHR: 3
variants count (.vcf): 60401
60401
0:00:05.776615 - data read.
0:00:03.716828 - estimation.
3/18
CHR: 4
variants count (.vcf): 59229
59229
0:00:05.569617 - data read.
0:00:02.457354 - estimation.
4/18
CHR: 5
variants count (.vcf): 49171
49171
0:00:04.767476 - data read.
0:00:01.376554 - estimation.
5/18
CHR: 6
variants count (.vcf): 70018
70018
0:00:06.583272 - data read.
0:00:04.086099 - estimation.
6/18
CHR: 7
variants count (.vcf): 55956
55956
0:00:05.405496 - data read.
0:00:02.610067 - estimation.
7/18
CHR: 8
variants count (.vcf): 60357
60357
0:00:05.752318 - data read.
0:00:03.248486 - estimation.
8/18
CHR: 9
variants count (.vcf): 60767
60767
0:00:05.700133 - data read.
0:00:03.269038 - estimation.
9/18
CHR: 10
variants count (.vcf): 48563
48563
0:00:04.867772 - data read.
0:00:00.634116 - estimation.
10/18
CHR: 11
variants count (.vcf): 41631
41631
0:00:04.094702 - data read.
0:00:00.996695 - estimation.
11/18
CHR: 12
variants count (.vcf): 39134
39134
0:00:03.819300 - data read.
0:00:00.606593 - estimation.
12/18
CHR: 13
variants count (.vcf): 64634
64634
0:00:06.140075 - data read.
0:00:07.494665 - estimation.
13/18
CHR: 14
variants count (.vcf): 58658
58658
0:00:05.559844 - data read.
0:00:02.084514 - estimation.
14/18
CHR: 15
variants count (.vcf): 52374
52374
0:00:04.991585 - data read.
0:00:02.783985 - estimation.
15/18
CHR: 16
variants count (.vcf): 40184
40184
0:00:03.931317 - data read.
0:00:00.740563 - estimation.
16/18
CHR: 17
variants count (.vcf): 37522
37522
0:00:03.692432 - data read.
0:00:00.484235 - estimation.
17/18
CHR: 18
variants count (.vcf): 30373
30373
0:00:03.027845 - data read.
0:00:00.453496 - estimation.
18/18

estimating parameters...
cm min: 0.5
cm max: 30

free variables: t1 t2 m1 m2 mt
Traceback (most recent call last):
  File "/public/home/qiuyb/LaNeta-main/laneta.py", line 130, in <module>
    parameters = exp.estimateTwoPulse(cm_max=clargs.max,
  File "/public/home/qiuyb/LaNeta-main/LaNeta/ThLd.py", line 816, in estimateTwoPulse
    parameters = self.estimate_parameters(T1=T1, T2=T2, M1=M1, M2=M2,
  File "/public/home/qiuyb/LaNeta-main/LaNeta/ThLd.py", line 961, in estimate_parameters
    res = least_squares(metr, x0, bounds=(_bounds, bounds_))
  File "/public/home/qiuyb/miniconda3/envs/conda_laneta/lib/python3.9/site-packages/scipy/optimize/_lsq/least_squares.py", line 827, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.
`

**Comment by danimfernandes** [comment]
This is old, but I have the same exact issue. Managed to run it with no issues, but I get the same final result, and with .ld file full of "nan" and "0". Would love to know how to fix this.

**Comment by danimfernandes** [comment]
Hi again. By increasing the -b parameter I was able to run with no error. I had to bump -b to at least 0.5 for it to finish, although I haven't yet checked if the results are fine or not.
